+{
    classes => [
        "_User",
        "Child",
        "ChildImage1",
        "ChildImage2",
        "Comment1",
        "Comment2",
        "EmailVerify",
        "Config",
        "FamilyApply",
        "FamilyRole",
        "PartnerApply",
        "PincodeList",
        "NotificationHistory",
        "PushNotificationEvent",
        "ShardConf",
        "TutorialMap"
    ],
    backupToMySQL => [
        "_User",
        "Child",
        "ChildImage1",
        "ChildImage2",
        "Comment1",
        "Comment2",
        "EmailVerify",
        "FamilyRole",
        "PartnerApply",
        "NotificationHistory",
        "PushNotificationEvent",
        "TutorialMap",
        "CritLog",
        "InfoLog",
        "TrackingLog",
    ],
    logClasses => [
        "CritLog",
        "WarnLog",
        "InfoLog"
    ],
    imageClasses => [
        "ChildImage1",
        "ChildImage2",
    ],
    staffFamilyId => [
        "fxUbOL",
        "fVinLR",
        "few8LR",
        "fcRMSh",
        "f7EVuY",
        "fzdLFU",
        "fuSNUH",
    ],
}
